name: Docker

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch:

# automatically cancel in-progress builds if another commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: dockerfile-cli
        run: |
          docker build \
            --build-arg LIGHTGBM_GIT_REF=${{ github.sha }} \
            - < ./docker/dockerfile-python
      - name: dockerfile-r
        run: |
          docker build \
            --build-arg LIGHTGBM_GIT_REF=${{ github.sha }} \
            - < ./docker/dockerfile-r
      - name: dockerfile-python
        run: |
          docker build \
            --build-arg LIGHTGBM_GIT_REF=${{ github.sha }} \
            - < ./docker/dockerfile-python
      - name: dockerfile.gpu
        run: |
          docker build \
            --build-arg LIGHTGBM_GIT_REF=${{ github.sha }} \
            - < ./docker/gpu/dockerfile.gpu
      - name: dockerfile-cli-only.gpu
        run: |
          docker build \
            --build-arg LIGHTGBM_GIT_REF=${{ github.sha }} \
            - < ./docker/gpu/dockerfile-cli-only.gpu
      - name: dockerfile-cli-only-distroless.gpu
        run: |
          docker build \
            --build-arg LIGHTGBM_GIT_REF=${{ github.sha }} \
            - < ./docker/gpu/dockerfile-cli-only-distroless.gpu
  all-docker-jobs-successful:
    if: always()
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Note that all tests succeeded
      uses: re-actors/alls-green@v1.2.2
      with:
        jobs: ${{ toJSON(needs) }}
